### ISSUE TITLE
Handle YAML test output

### ISSUE THREAD

**Issue by smerrell** [smerrell/tap_parser#8]
Parse YAML blocks when given as test output. This will be a little interesting since there isn't a solid standard for what the YAML blocks are supposed to look like. The harness could at least handle something like this given from the TAP spec, otherwise it probably should just output the keys and values in a nice way.

```
not ok 3 Resolve address
 ---
 message: "Failed with error 'hostname peebles.example.com not found'"
 severity: fail
 data:
   got:
     hostname: 'peebles.example.com'
     address: ~
   expected:
     hostname: 'peebles.example.com'
     address: '85.193.201.85'
 ...
```
